%%
%obtain data in matrix form from struct generated by wavefront.m file

clear all;
NumPar=10;%Number of parameter set
NumPoint=50;%Number of data point per each set
NumData=NumPar*NumPoint;%Total number of Data
SR=zeros(NumData,1);
EC=zeros(NumData,1);
PV=zeros(NumData,1);
RMS=zeros(NumData,1);
GRMS=zeros(NumData,1);
GPV=zeros(NumData,1);
for i=1:10
load(['E:\\WavefrontData\\par_',num2str(i),'.mat']);
    for j=1:numel(parameter)
        idx=(i-1)*50+j;
        SR(idx)=parameter(j).SR;
        EC(idx)=parameter(j).EC;
        PV(idx)=parameter(j).PV;
        RMS(idx)=parameter(j).RMS;
        GRMS(idx)=parameter(j).GRMS;
        GPV(idx)=parameter(j).GPV;
    end
        clear parameter 
end
save ('prodata.mat','SR','EC','PV','RMS','GRMS','GPV');