%%
%obtain data in matrix form from struct generated by wavefront.m file

clear all;
dirs=dir('E:\Wavefront20150513\*.mat');   % 用你需要的目录以及文件扩展名替换。读取某个目录的指定类型文件列表，返回结构数组。
dircell=struct2cell(dirs)' ;    % 结构体(struct)转换成元胞类型(cell)，转置一下是让文件名按列排列。
filenames=dircell(:,1);   % 第一列是文件名
NumPar=numel(filenames);%Number of para_same set
NumPoint=50;%Number of data point per each set
NumData=NumPar*NumPoint;%Total number of Data
SR=zeros(NumData,1);
SRdl=SR;
ECdl=SR;
rof80x=SR;
rof80y=SR;
EC=zeros(NumData,1);
PV=zeros(NumData,1);
RMS=zeros(NumData,1);
GRMS=zeros(NumData,1);
GPV=zeros(NumData,1);
for i=1:NumPar
load(['E:\Wavefront20150513\',char(filenames(i))]);
    for j=1:numel(para_same)
        idx=(i-1)*50+j;
        SR(idx)=para_same(j).SR;
        SRdl(idx)=para_same(j).SRdl;
        ECdl(idx)=para_same(j).ECdl;
        rof80x(idx)=para_same(j).rof80(1);
        rof80y(idx)=para_same(j).rof80(2);
        PV(idx)=para_same(j).PV;
        RMS(idx)=para_same(j).RMS;
        GRMS(idx)=para_same(j).GRMS;
        GPV(idx)=para_same(j).GPV;
    end
        clear para_same 
end
save ('E:\Wavefront20150513\parsamedata.mat','SR','SRdl','ECdl','rof80x','rof80y','PV','RMS','GRMS','GPV');